import mongoose from "mongoose";

const OptimizationSchema = new mongoose.Schema(
    {
        user: {
            type: mongoose.Schema.Types.ObjectId,
            required: true,
            ref: "User",
        },
        name: {
            type: String,
            required: true,
            default: "Untitled Optimization",
        },
        provider: {
            type: String,
            required: true,
        },
        providerName: {
            type: String,
            required: true,
        },
        instanceType: {
            type: String,
            required: true,
        },
        status: {
            type: String,
            required: true,
            enum: ['Optimal', 'Underutilized', 'Overutilized'],
        },
        // The raw input configuration submitted by the user
        inputConfig: {
            type: Object,
            required: true,
        },
        // The raw prediction output result block generated by the ML
        predictionResult: {
            type: Object,
            required: true,
        }
    },
    {
        timestamps: true,
    }
);

export default mongoose.model("Optimization", OptimizationSchema);
